version: '3.0'

services:
  webserver:
    container_name: phpProject-web
    build:
      context: .
      dockerfile: Dockerfile.web
    volumes:
      - .:/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    port:
      - 8080:80

  app:
    container_name: firstProject-app
    build:
      context: .
      dockerfile: Dockerfile.app
    volumes:
      - .:/app
